Lab2.2/Models/CalcModel.cs
using System;

namespace Lab2._2.Models
{
    public class CalcModel
    {
        public string first { get; set; }
        public string second { get; set; }
        public string sign { get; set; }
        public int result;

        public bool show = false;
        public bool divNull;
        public bool Empty;
        public bool Unknown;
        public void calculation()
        {
            char signChar = Convert.ToChar(sign);
            divNull = false;
            Unknown = false;
            int temp;
            if (int.TryParse(first, out temp) && int.TryParse(second, out temp))
            {
                Empty = false;
            }
            else
            {
                Empty = true;
                return;
            }
            int firstNum = Int32.Parse(first);
            int secondNum = Int32.Parse(second);
            switch (signChar)
            {
                case '+':
                    result = firstNum + secondNum;
                    break;
                case '-':
                    result = firstNum - secondNum;
                    break;
                case '*':
                    result = firstNum * secondNum;
                    break;
                case '/':
                    if (secondNum == 0)
                        divNull = true;
                    else
                        result = firstNum / secondNum;
                    break;
                default:
                    Unknown = true;
                    break;
            }

        }
    }
}

Lab2.2/Controllers/CalcController.cs
using Lab2._2.Models;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Diagnostics;

namespace Lab2._2.Controllers
{
    public class CalcController : Controller
    {
        private readonly ILogger<CalcController> _logger;

        public CalcController(ILogger<CalcController> logger)
        {
            _logger = logger;
        }

        public IActionResult ManualParsingInSingleAction()
        {
           if (Request.Method != "POST")
               return View();
            else
            {
                CalcModel model = new CalcModel();
                model.first = Request.Form["first"];
                model.second = Request.Form["second"];
                model.sign = Request.Form["sign"];
                model.show = true;
                model.calculation();
                ViewBag.dataModel = model;
                return View("Results");
            }
        }
        [HttpGet]
        public IActionResult ManualParsingInSeparateActions()
        {
            return View();
        }
        [HttpPost]
        public IActionResult ManualParsingInSeparateActions(int temp)
        {
            CalcModel model = new CalcModel();
            model.first = Request.Form["first"];
            model.second = Request.Form["second"];
            model.sign = Request.Form["sign"];
            model.show = true;
            model.calculation();
            ViewBag.dataModel = model;
            return View("Results");
        }
        [HttpGet]
        public IActionResult ModelBindingParametrs()
        {
            return View();
        }
        [HttpPost]
        public IActionResult ModelBindingParametrs(string first, string second, string sign)
        {
            CalcModel model = new CalcModel();
            model.first = Request.Form["first"];
            model.second = Request.Form["second"];
            model.sign = Request.Form["sign"];
            model.show = false;
            model.calculation();
            ViewBag.dataModel = model;
            return View("Results");
        }
        [HttpGet]
        public IActionResult ModelBindingSeparateModel()
        {

            return View();
        }
        [HttpPost]
        public IActionResult ModelBindingSeparateModel(CalcModel model)
        {
            model.show = false;
            model.calculation();
            ViewBag.dataModel = model;
            return View("Results");
        }
    }
}

Lab2.2/Controllers/HomeController.cs
using Lab2._2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab2._2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Lab2.2/Views/Calc/ManualParsingInSeparateActions.cshtml
@{
    ViewData["Title"] = "ManualParsingInSeparateActions";
}

<h1>ManualParsingInSeparateActions</h1>
<div class="calculations">
    <form method='post'>
        <input type='number' name='first'class="in"><br>
        <select name="sign">
            <option value="+">+</option>
            <option value="-">-</option>
            <option value="*">*</option>
            <option value="/">/</option>
        </select><br>
        <input type='number' name='second' class="in"><br>
        <input type='submit' value='Submit' class="sub">
    </form>
</div>

Lab2.2/Views/Calc/ManualParsingInSingleAction.cshtml
@{
    ViewData["Title"] = "ManualParsingInSingleAction";
}

<h1>ManualParsingInSingleAction</h1>
<div class="calculations">
    <form method='post'>
        <input type='number' name='first' class="in"><br>
        <select name="sign">
            <option value="+">+</option>
            <option value="-">-</option>
            <option value="*">*</option>
            <option value="/">/</option>
        </select><br>
        <input type='number' name='second' class="in"><br>
        <input type='submit' value='Submit' class="sub">
    </form>
</div>

Lab2.2/Views/Calc/ModelBindingParametrs.cshtml
@{
    ViewData["Title"] = "ModelBndingParametrs";
}

<h1>ModelBndingParametrs</h1>
<div class="calculations">
    <form method='post'>
        <input type='number' name='first'class="in"><br>
        <select name="sign">
            <option value="+">+</option>
            <option value="-">-</option>
            <option value="*">*</option>
            <option value="/">/</option>
        </select><br>
        <input type='number' name='second' class="in"><br>
        <input type='submit' value='Submit' class="sub">
    </form>
</div>

Lab2.2/Views/Calc/ModelBindingSeparateModel.cshtml
@{
    ViewData["Title"] = "ModelBindingSeparateModel";
}

<h1>ModelBindingSeparateModel</h1>
<div class="calculations">
    <form method='post'>
        <input type='number' name='first'class="in"><br>
        <select name="sign">
            <option value="+">+</option>
            <option value="-">-</option>
            <option value="*">*</option>
            <option value="/">/</option>
        </select><br>
        <input type='number' name='second' class="in"><br>
        <input type='submit' value='Submit' class="sub">
    </form>
</div>

Lab2.2/Views/Calc/Results.cshtml
@{
    ViewData["Title"] = "Results";
}

<h1>Results</h1>
<div class="calculations">
    <div class="results">
        @if (ViewBag.dataModel.Empty || ViewBag.dataModel.divNull || ViewBag.dataModel.Unknown)
        {
            @if (ViewBag.dataModel.Empty)
            {
                <div>Error! You need enter all numbers.</div>
            }

            @if (ViewBag.dataModel.divNull)
            {
                <div>Error! Divide by zero.</div>
            }

            @if (ViewBag.dataModel.Unknown)
            {
                <div>Unknown error.</div>
            }
        }
        else
        {
            @if (ViewBag.dataModel.show == false)
            {
                <div>@ViewBag.dataModel.result</div>
            }
            else
            {
                <div>@ViewBag.dataModel.first @ViewBag.dataModel.sign @ViewBag.dataModel.second = @ViewBag.dataModel.result</div>
            }
        }
    </div>
</div>

Lab2.2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Form parameters parsing demo</h1>
<ul type="disc">
    <li><a class="nav-link" asp-area="" asp-controller="Calc" asp-action="ManualParsingInSeparateActions">Manual parsing in separate actions</a></li>
    <li><a class="nav-link" asp-area="" asp-controller="Calc" asp-action="ManualParsingInSingleAction">Manual parsing in single action</a></li>
    <li><a class="nav-link" asp-area="" asp-controller="Calc" asp-action="ModelBindingParametrs">Model binding (parameters)</a></li>
    <li><a class="nav-link" asp-area="" asp-controller="Calc" asp-action="ModelBindingSeparateModel">Model binding (separate model)</a></li>
</ul>

Lab2.2/Views/Service/ManualParsingInSeparateActions.cshtml
@{
    ViewData["Title"] = "ManualParsingInSeparateActions";
}

<h1>ManualParsingInSeparateActions</h1>
<div class="calculations">
    <form method='post'>
        <input type='number' name='firstNum'><br>
        <select name="operation">
            <option value="+">+</option>
            <option value="-">-</option>
            <option value="*">*</option>
            <option value="/">/</option>
        </select><br>
        <input type='number' name='secondNum'><br>
        <input type='submit' value='Submit'>
    </form>
</div>

Lab2.2/Views/Service/ManualParsingInSingleAction.cshtml
@{
    ViewData["Title"] = "ManualParsingInSingleAction";
}

<h1>ManualParsingInSingleAction</h1>
<div class="calculations">
    <form method='post'>
        <input type='number' name='firstNum'><br>
        <select name="operation">
            <option value="+">+</option>
            <option value="-">-</option>
            <option value="*">*</option>
            <option value="/">/</option>
        </select><br>
        <input type='number' name='secondNum'><br>
        <input type='submit' value='Submit'>
    </form>
</div>

Lab2.2/Views/Service/ModelBindingParametrs.cshtml
@{
    ViewData["Title"] = "ModelBndingParametrs";
}

<h1>ModelBndingParametrs</h1>
<div class="calculations">
    <form method='post'>
        <input type='number' name='firstNum'><br>
        <select name="operation">
            <option value="+">+</option>
            <option value="-">-</option>
            <option value="*">*</option>
            <option value="/">/</option>
        </select><br>
        <input type='number' name='secondNum'><br>
        <input type='submit' value='Submit'>
    </form>
</div>

Lab2.2/Views/Service/ModelBindingSeparateModel.cshtml
@{
    ViewData["Title"] = "ModelBndingSeparateModel";
}

<h1>ModelBndingSeparateModel</h1>
<div class="calculations">
    <form method='post'>
        <input type='number' name='firstNum'><br>
        <select name="operation">
            <option value="+">+</option>
            <option value="-">-</option>
            <option value="*">*</option>
            <option value="/">/</option>
        </select><br>
        <input type='number' name='secondNum'><br>
        <input type='submit' value='Submit'>
    </form>
</div>

Lab2.2/Views/Service/Results.cshtml
@{
    ViewData["Title"] = "Result";
}

<h1>Result</h1>
<div class="calculations">
    <div class="result">
        @if (ViewBag.dataModel.Empty || ViewBag.dataModel.divNull || ViewBag.dataModel.Unknown)
        {
            @if (ViewBag.dataModel.Empty)
            {
                <div>Error! You need enter all numbers.</div>
            }

            @if (ViewBag.dataModel.divNull)
            {
                <div>Error! Divide by zero.</div>
            }

            @if (ViewBag.dataModel.Unknown)
            {
                <div>Unknown error.</div>
            }
        }
        else
        {
            @if (ViewBag.dataModel.show == false)
            {
                <div>@ViewBag.dataModel.resNum</div>
            }
            else
            {
                <div>@ViewBag.dataModel.firstNum @ViewBag.dataModel.operation @ViewBag.dataModel.secondNum = @ViewBag.dataModel.resNum</div>
            }
        }
    </div>
</div>

Lab2.2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab2._2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab2._2.styles.css" asp-append-version="true" />
</head>
    <body>
        <header>
            <a asp-area="" asp-controller="Home" asp-action="Index">Backend2</a>
            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </header>

        <div class="main">
            @RenderBody()
        </div>

        <div class="line"></div>
        <footer>&copy; 2022 - Backend2</footer>
    </body>
</html>